description: "My eval"

prompts:
  - "{{job_posting}}"

providers:
  - file://C:/Users/gvvsn/OneDrive/Desktop/Learning/LLM-ouput-formating/provider.py
  
tests:
  - vars:
      job_index: 0

    assert:
      - type: icontains
        value: Senior Technical Program Manager
      - type: icontains
        value: Google
      - type: icontains
        value: $192,000 - $278,000

  - vars:
      job_index: 1

    assert:
      - type: icontains
        value: Senior Technical Program Manager
      - type: icontains
        value: Google
      - type: icontains
        value: $192,000 - $278,000

  - vars:
      job_index: 2

    assert:
      - type: icontains
        value: Senior Technical Program Manager
      - type: icontains
        value: Google
      - type: icontains
        value: $192,000 - $278,000
    