# Github UI name
name: CI 

# run on every push to any branch
on:
  push:
    branches: ["*"]

# one job quality running on Ubuntu
jobs:
  quality:
    runs-on: ubuntu-latest

    # sequential steps to run
    steps:
      - name: Checkout code               # Downloads the repo to that Ubuntu VM
        uses: actions/checkout@v4

      - name: Set up Python 3.11          # Installs python, pip cached: faster after first run
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dev tools           # Installs ruff and black ont that VM
        run: pip install -r requirements.txt

      - name: Lint with ruff              # Runs ruff against the code. If issue: job fails.
        run: ruff check .

      - name: Check formatting with black # Checks code is formatted correctly. --check explicitly means only checking pass/fail
        run: black --check .

      - name: Run tests
        # env:
        #   GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} , in github settings>secrets and variables> actions
        run: pytest tests/ -v